---
- name: Disable systemd-resolved
  tags: dns
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
  become: true

- name: Remove symlink resolv.conf
  tags: dns
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  become: true

- name: Set DNS in Resolv.conf
  tags: dns
  ansible.builtin.template:
    src: templates/resolv.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  become: true
